name: macOS

on:
  pull_request:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    # Install system dependencies
    - name: Install Dependancies
      run: |
        brew install SDL2

    # Build the lib
    - name: Build MacroLibX
      run: make -j && make fclean && make debug 

    # Build the example
    - name: Build Example
      run: cd example && bash ./build.sh

